# === NOMBRE DE LA APLICACIÓN ===
spring.application.name=mobileFlex

# === CONFIGURACIÓN DE H2 EN MEMORIA ===
spring.datasource.url=jdbc:h2:mem:mobilefix_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# === HIBERNATE / JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# === CONSOLA WEB DE H2 ===
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

